// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwZ6jWpGpz4JjJbHda8DAzkraj0cqypqI',
    appId: '1:6028500156:web:c9ca4059347acc774384b9',
    messagingSenderId: '6028500156',
    projectId: 'complete-e-commerce-app',
    authDomain: 'complete-e-commerce-app.firebaseapp.com',
    storageBucket: 'complete-e-commerce-app.appspot.com',
    measurementId: 'G-JHC55GX7VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJQLZIGbTlSmfFxdVAw4jMv4nqADPJzac',
    appId: '1:6028500156:android:dbdaf6f2d2ac41614384b9',
    messagingSenderId: '6028500156',
    projectId: 'complete-e-commerce-app',
    storageBucket: 'complete-e-commerce-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtoMTdIbEShghdxz0wLW_kLIkClRUgJrI',
    appId: '1:6028500156:ios:2c88a621cfa44d6a4384b9',
    messagingSenderId: '6028500156',
    projectId: 'complete-e-commerce-app',
    storageBucket: 'complete-e-commerce-app.appspot.com',
    iosClientId: '6028500156-0afs0sr0i14j03rgak91baehrqhn77pn.apps.googleusercontent.com',
    iosBundleId: 'com.example.completeECommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtoMTdIbEShghdxz0wLW_kLIkClRUgJrI',
    appId: '1:6028500156:ios:2c88a621cfa44d6a4384b9',
    messagingSenderId: '6028500156',
    projectId: 'complete-e-commerce-app',
    storageBucket: 'complete-e-commerce-app.appspot.com',
    iosClientId: '6028500156-0afs0sr0i14j03rgak91baehrqhn77pn.apps.googleusercontent.com',
    iosBundleId: 'com.example.completeECommerceApp',
  );
}
